import { Translations } from './types';

export const fr: Translations = {
    // Commun
    back: "↩️ Retour",
    currencySymbol_solana: "SOL",
    currencySymbol_ethereum: "ETH",
    refresh: "🔄 Actualiser",
    cancel: "❌ Annuler",
    confirm: "✅ Confirmer",
    close: "❌ Fermer",
    backWallet: "⬅ Retour Wallet",
    backMenu: "⬅ Retour menu",
    backSettings: "⬅ Retour paramètres",
    totals: "Total",

    //commands
    commands: {
        start: "Commencez avec FoxyBoTracker.",
        menu: "Accédez au menu principal de FoxyBoTracker.",
        setting: "Afficher les paramètres de FoxyBoTracker.",
        wallet: "Afficher vos Wallets FoxyBoTracker.",
        sniper: "Lancer le module de Snipping de FoxyBoTracker.",
        position: "Afficher vos positions sur FoxyBoTracker.",
        help: "Centre d'aide",
        chains: "Choisissez votre Blockchain préférée pour le Trading avec FoxyBoTracker."
    },

    // Admin
    admin: {
        p1: "🌠 Bienvenue, Admin",
        p2: "Vous pouvez gérer le <b>système de Whitelist</b> en ajoutant ou supprimant des utilisateurs selon vos besoins.",
        addUser: "Ajouter un utilisateur",
        removeUser: "Supprimer un utilisateur",
        addSniperUser: "Ajouter un utilisateur au Sniper",
        removeSniperUser: "Supprimer un utilisateur du Sniper",
        tipPercentage: "💰 Frais de pourboire (%) - (Solana)",
        tipPercentageEth: "💰 Frais de pourboire (%) - (Ethereum)",
        adminWallet: "💼 Wallet Admin",
        adminWalletName: "📝 Nom du Wallet Admin",
        solanaPrice: "Prix du Solana",
        p3: "Adresse du Wallet Admin",
        p4: "Solde du Wallet Admin",
        whitelistActive: "Whitelist activé",
        whitelistInactive: "Whitelist desactivé",
        walletName: "Aucun",
        referral: "Récompense 10 parrainages",
        wallet: "💼 Limite de Wallet",
        referralSettings: "Paramètres des parrainages"
    },

    //welcome
    welcome: {
        p1: "Accès restreint – Autorisation requise !",
        p2: "Bonjour",
        p3: "FoxyBoTracker est un service privé fourni par The CryptoFox Learning.",
        p4: "Votre identifiant Telegram n'est actuellement pas répertorié dans notre liste d'accès autorisé. (Whitelist)",
        p5: "L'accès est strictement limité aux utilisateurs qui ont été approuvés par notre équipe.",
        p6: "Pour y accéder, vous devez d’abord visiter notre site officiel et suivre le processus d’accès.",
        p7: "Une fois votre demande soumise, un administrateur vous contactera pour approuver ou refuser votre entrée dans la Whitelist.",
        request: "✅ Demande d'accès",
        visit: "🌐 Visitez le site Web",
        admin: "👑 Menu Admin"
    },

    //Referral
    referral: {
        p1: "🎁 Programme de parrainage 🎁",
        p2: "Invitez vos amis et gagnez des récompenses exclusives avec FoxyBoTracker 🚀",
        p3: "👥 Utilisateurs parrainés",
        p4: "💰 Récompenses",
        p5: "🔗 Votre lien de parrainage",
        p6: "Recevez un Wallet",
        p7: "Partagez ce lien avec vos amis ! Chaque inscription via votre lien = Plus de profits pour vous ✨",
        p8: "Vous recevez",
        p9: "pour chaque lot de",
        p10: "parrainages",
        wallet: "💼 Configurer un Wallet pour les commissions",
        share: "📥 Partagez votre lien de parrainage",
        openLink: "Ouvrir le lien de parrainage",
        message1: "Veuillez saisir votre Wallet pour les commissions.",
        message2: "Adresse de Wallet invalide. Réessayez !",
        message3: "Adresse de Wallet invalide.",
        shareMessage1: "FoxyBoTracker est le meilleur BOT de Trading !",
        shareMessage2: "Gérez vos cryptomonnaies Solana plus rapidement que jamais grâce aux achats et ventes instantanés, au suivi en temps réel de vos positions et au contrôle total de votre Wallet directement depuis Telegram.",
        shareMessage3: "Votre lien de parrainage :",
        share1: "📥 Partager",
        viewList: "📋 Voir la liste des parrainages",
        listTitle: "📋 Liste des filleuls parrainés via votre lien de parrainage FoxyBoTracker",
        totalReferrals: "Total des parrainages",
        noReferrals: "Vous n’avez pas encore de filleul. Partagez votre lien de parrainage pour commencer à gagner des SOL.",
        listHeader: "Parrainages :",
        date: "Date",
        pageInfo: "Page",
        prev: "Précédent",
        next: "Suivant"

    },

    // Menu
    menu: {
        p1: "🌠 Bonjour",
        p2: "Menu principal de FoxyBoTracker :",
        p3: 'Gérez et Tradez vos cryptomonnaies sur Solana plus rapidement que jamais : Achats et ventes instantanés, suivi en temps réel de vos positions et contrôle total de vos Wallets, directement depuis Telegram.',
        p3_ethereum: 'Gérez et Tradez vos cryptomonnaies sur Ethereum plus rapidement que jamais : Achats et ventes instantanés, suivi en temps réel de vos positions et contrôle total de vos Wallets, directement depuis Telegram.',
        p4: "Votre Wallet Solana :",
        p5: "Bénéficiez de Transactions sécurisées, de prix en temps réel et de frais optimisés pour exécuter chaque mouvement avec précision sur la Blockchain Solana.",
        p5_ethereum: "Bénéficiez de Transactions sécurisées, de prix en temps réel et de frais optimisés pour exécuter chaque mouvement avec précision sur la Blockchain Ethereum.",
        p6: "Une fois vos Wallets de Trading créés, vous pouvez ouvrir, fermer et gérer vos positions instantanément depuis FoxyBoTracker, sans jamais quitter Telegram.",
        buy: "💰 Acheter",
        sell: "🎒 Vendre",
        wallet: "💼 Wallet",
        position: "📊 Position",
        settings: "⚙️ Paramètres",
        referral: "🎁 Parrainage",
        help: "🙋‍♂️ Aide",
        adminPanel: "👑 Admin",
        trendingCoin: "🥇 Token Hype",
        chain: "Blockchain sélectionnée :",
        chainButton: "🔗 Blockchain de Trading",
        botVersion: "🦊 Version de FoxyBoTracker Telegram :"
    },

    // Acheter
    buy: {
        p1: "💰 Menu d'achat",
        p2: "🌱 Ce Token est très récent. Soyez prudent.",
        p3: "Date de création du Token :",
        p4: "💸 Prix :",
        p5: "🏦 Liquidité :",
        p6: "📈 Capitalisation :",
        p7: "Renoncée",
        p8: "Freeze",
        p9: "Mint",
        p10: "💊 Progression de la Bonding Curve :",
        p11: "Paramètre de vente automatique",
        p12: "Statut",
        p13: "Niveau de Take profit :",
        p14: "Niveau de Stop loss :",
        p15: "🕒 Dernière mise à jour (UTC) :",
        p16: "💡 Sélectionnez une action ci-dessous.",
        p17: " ",
        p18: "j",
        p19: "Partagez le Token avec vos amis",
        settings: "⚙️ Paramètres",
        buy: "Acheter",
        default: "Défaut"
    },

    // Vendre
    sell: {
        p1: "🎒 Menu de vente",
        p2: "💸 Prix :",
        p3: "🏦 Liquidité :",
        p4: "📈 Capitalisation :",
        p5: "Renoncé",
        p6: "Gel",
        p7: "Mint",
        p8: "💰 Solde en Tokens :",
        p9: "Profit",
        p10: "💹 Prix moyen d'entrée (MC) :",
        p11: "🕒 Dernière mise à jour (UTC) :",
        p12: "💡 Sélectionnez une action ci-dessous.",
        p13: "Statut de vente automatique :",
        p14: "✅ Trade réussi, voici l'image PNL de votre performance.",
        p15: "Partagez le Token avec vos amis",
        settings: "⚙️ Paramètres",
        sell: "Vendre",
        default: "Défaut"
    },

    // Positions
    positions: {
        p1: "💼 Vos Positions dans FoxyBoTracker.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "💰 Solde en Tokens :",
        p5: "📉 Profit :",
        p6: "💹 Prix moyen d'entrée (MC) :",
        p7: "🕒 Dernière mise à jour (UTC) :",
        p8: "Aucune position active n’a été détectée à l’heure actuelle. Tous les Tokens ont déjà été vendus ou présentent un solde nul sur le Wallet.",
        importPosition: "Importer une position",
        noPositionsFound: "Aucune position trouvée. Commencez à Trader pour voir vos positions ici."
    },

    // Portefeuilles
    wallets: {
        p1: "💼 Réglages des Wallets FoxyBoTracker.",
        p2: "Votre Wallet Solana ou Ethereum :",
        p2_solana: "Votre Wallet Solana :",
        p2_ethereum: "Votre Wallet Ethereum :",
        p3: "❓ Si vous avez besoin d'aide",
        p4: "Cliquez ici !",
        p5: "⬇️ Créez, gérez, exportez et importez des Wallets à partir de ce menu.",
        p6: "💼 Vos Wallets Solana ou Ethereum",
        p6_solana: "💼 Vos Wallets Solana",
        p6_ethereum: "💼 Vos Wallets Ethereum",
        p7: "🦊 Astuce : Utilisez un Wallet dédié exclusivement au Trading, contenant uniquement les fonds nécessaires, et conservez vos actifs principaux dans un Wallet séparé.",
        p8: "🔒 Sécurité : Afin de protéger vos fonds, veillez à conserver vos Wallets FoxyBoTracker en dehors de tout BOT ou automatisation externe.",
        p9: "💡 Que souhaitez-vous faire :",
        p10: "Nbr. Max de Wallets autorisés dans FoxyBoTracker",
        settings: "⚙️ Paramètres",
        createWallet: "🆕 Créer Wallet",
        importWallet: "📥 Import. Wallet",
        deleteWallet: "🗑 Suppr. Wallet",
        renameWallet: "📝 Renom. Wallet",
        exportPrivateKey: "🔐 Export. clé privée",
        withdraw: "💸 Retrait",
        switch: "✅ Changer le Wallet par défaut",
    },

    // Paramètres
    settings: {
        p1: "💼 Réglages de FoxyBoTracker.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "🔒 Sécurité : Utilisez uniquement des paramètres de Trading adaptés à votre niveau de risque et à votre stratégie, afin d’éviter toute exposition excessive ou involontaire.",
        p5: "💡 Que souhaitez-vous faire :",
        fee: "⛽ Frais",
        slippage: "💦 Slippage",
        wallet: "💳 Wallets",
        language: "🌏 Langue",
        quickBuy: "⚡ Achat rapide",
        quickSell: "💰 Vente rapide",
        young: "🌱 Token récent",
        autoImage: "Image PNL automatique",
        autoSell: "🕹️ Vente automatique",
        mev: "Protection MEV"
    },

    // Aide
    help: {
        p1: "Aide & Support.",
        p2: "📚 Pour les FAQ, guides et tutoriels, veuillez visiter notre Site Officiel.",
        p3: "🐦 Pour suivre les dernières mises à jour et actualités concernant les modifications et évolutions de FoxyBoTracker, consultez notre changelog ou nos réseaux sociaux.",
        p4: "💬 Besoin d'aide ? Contactez notre Responsable Support ci-dessous.",
        p5: "Nous sommes là pour vous 24/7 !",
        documentation: "📚 Guide de démarrage Tracker ETH",
        contactSupport: "💬 Contacter notre support",
        changelogs: "📢 Changelog"
    },

    // Changer de portefeuille par défaut
    switch: {
        p1: "🔁 Changer de Wallet",
        p2: "Wallet actif :",
        p3: "Adresse :",
        p4: "Nom :",
        p5: "Solde du Wallet :",
        p6: "✅ indique le Wallet actif",
        p7: "🔓 indique que le Wallet a été exporté",
        p8: "Pour passer à un autre Wallet, cliquez sur son adresse ci-dessous"
    },

    //Create wallet
    createWallet: {
        p1: "Comment souhaitez-vous nommer votre nouveau Wallet ?",
        p2: "Le nom du Wallet ne peut pas contenir de symboles ou de caractères spéciaux.",
        p3: "Un Wallet avec ce nom existe déjà. Veuillez réessayer.",
        p4: "✅ Wallet FoxyBoTracker créé !",
        p5: "💳 Nom : ",
        p6: "🔗 Adresse : ",
        p7: "🔑 Clé privée : ",
        p8: "⚠️ Gardez votre clé privée en sécurité. FoxyBoTracker ne se souviendra plus de votre clé privée et vous ne pourrez plus la récupérer après ce message. Veuillez importer votre Wallet dans MetaMask.",
        p9: "⚠️ Gardez votre clé privée en sécurité. FoxyBoTracker ne se souviendra plus de votre clé privée et vous ne pourrez plus la récupérer après ce message. Veuillez importer votre Wallet dans Phantom.",
        p10: "💡 Pour voir vos autres Wallets, allez dans les paramètres.",
        p11: "⚙️ Paramètres",
    },

    // Importer un portefeuille
    importWallet: {
        p1: "✅ Wallet importé avec succès !",
        p2: "💳 Nom :",
        p3: "🔗 Adresse :",
        p4: "💡 Pour voir vos autres Wallets, rendez-vous dans les paramètres.",
        settings: "⚙️ Paramètres",
    },

    // Renommer un portefeuille
    renameWallet: {
        p1: "✏️ Renommer le Wallet",
        p2: "💡 Sélectionnez un Wallet à renommer."
    },

    // Supprimer un portefeuille
    deleteWallet: {
        p1: "🗑️ Supprimer le Wallet",
        p2: "💡 Sélectionnez un Wallet à supprimer.",
        p3: "Êtes-vous sûr de vouloir supprimer ce Wallet",
        p4: "Cette action est irréversible.",
        delete: "🗑️ Supprimer"
    },

    // Retrait
    withdrawWallet: {
        p1: "💸 Retrait",
        p2: "💡 Sélectionnez un Wallet depuis lequel retirer des fonds.",
    },

    //Default wallet
    defaultWallet: {
        p1: "💳 Changer le Wallet par Défaut",
        p2: "💡 Sélectionnez un Wallet que vous souhaitez définir par défaut.",
    },

    // Zone dangereuse
    dangerZoneMessage: {
        p1: "⚠️ Zone dangereuse !",
        p2: "Soyez prudent, l'exportation de votre clé privée est une opération dangereuse.",
        p3: "Quiconque",
        p4: "avec accès à votre clé privée peut accéder à votre Wallet et voler vos fonds.",
        p5: "NOUS NE GARANTIRONS PLUS LA SÉCURITÉ DE VOS FONDS.",
        p6: "Êtes-vous sûr de vouloir continuer ?",
        exportPrivateKey: "🔑 Exporter",
    },

    // Exporter la clé privée
    exportPrivateKey: {
        p1: "🔐 Exporter la clé privée",
        p2: "💡 Sélectionnez le Wallet que vous souhaitez exporter."
    },

    // Clé privée
    privateKey: {
        p1: "🔐 Wallet :",
        p2: "Adresse :",
        p3: "🔑 Clé privée :",
        p4: "Voir sur Solscan",
        p5: "NE LA PARTAGEZ AVEC PERSONNE",
        p6: "Gardez La en lieu sûr, car elle donne un accès complet à votre Wallet et vos fonds",
        p7: "Une fois terminé, appuyez sur le bouton \"SUPPRIMER LE MESSAGE\" ci dessous",
        revealKey: "🔐 Afficher la clé",
        deleteMessage: "🗑️ Supprimer le message"
    },

    // Paramètres des frais
    feeSettings: {
        p1: "⛽️ Paramètres des frais",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "Rapide ⚡ : Utilise environ 0.001 SOL par transaction",
        p4_ethereum: "Rapide ⚡ : Utilise environ 0.0001 ETH par transaction",
        p5: "Rapide ⚡⚡ : Utilise environ 0.005 SOL par transaction",
        p5_ethereum: "Rapide ⚡⚡ : Utilise environ 0.0005 ETH par transaction",
        p6: "💡 Augmenter vos frais d'achat et de vente accélérera la prise en compte de la transaction on-chain.",
        p7: "⚠️ Vous devez entrer une valeur entre 0 et 1 pour chaque mise à jour de frais.",
        p8: "Lent",
        p9: "Normal",
        p10: "Rapide",
        p11: "🤖 Paramètres de frais recommandés",
        p12: "❓ Si vous avez besoin d'aide",
        p13: "Cliquez ici !",
        p14: "🌎 Frais recommandés actuels :",
        p15: "💡 Laisser FoxyBoTracker calculer automatiquement le pourboire MEV recommandé.",
        p16: "⚡ Vitesse des frais :",
        p17: "Ultra Rapide",
        buyFee: "⛽Frais d'achat :",
        sellFee: "⛽Frais de vente :",
        buyTip: "💸 Astuce achat :",
        sellTip: "💸 Astuce vente :",
        gasFeeSettingsEthereum: "⛽️ Paramètres des Frais de Gaz (Ethereum)",
        configureGasFeeEthereum: "💡 Configurez vos valeurs de frais de gaz pour les Transactions Ethereum.",
        currentGasValues: "Valeurs de Gaz Actuelles :",
        gasValue1: "⛽ Valeur de Gaz 1 :",
        gasValue2: "⛽ Valeur de Gaz 2 :",
        gasValue3: "⛽ Valeur de Gaz 3 :",
        veryFast: "Très Rapide",
        low: "Faible",
        recommendedGasFeeSettings: "⛽️ Paramètres de Frais de Gaz Recommandés",
        currentRecommendedGas: "🌎 Gaz Recommandé Actuel :",
        autoCalculateGasPrice: "💡 Laissez FoxyBoTracker calculer automatiquement le prix de gaz recommandé.",
        recommendedFeeSettings: "⛽️ Paramètres de Frais Recommandés",
        currentRecommendedFee: "🌎 Frais Recommandé Actuel :",
        autoCalculateMEVTip: "💡 Laissez FoxyBoTrackeer calculer automatiquement le pourboire MEV recommandé.",
        slowButton: "⚡ Lent",
        fastButton: "🚀 Rapide",
        normalButton: "⚡️ Normal",
        slowButton2: "🐢 Lent",
        enterGasFee: "Entrez les frais de gaz en Gwei (Exemple : 10, 50, 100) :",
        invalidGasFee: "Frais de gaz invalides. Veuillez entrer un nombre valide."
    },

    // Paramètres de glissement
    slippageSettings: {
        p1: "💦 Paramètres de Slippage.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "💡 Augmenter le pourcentage de slippage permet de faciliter l’exécution des transactions. À titre d’exemple, un slippage de 50 % accroît significativement les chances de validation de l’ordre.",
        buy: "💦 Achat :",
        sell: "💦 Vente :"
    },

    // Langue
    language: {
        p1: "Veuillez sélectionner la langue de FoxyBoTracker.",
        english: "Anglais",
        french: "Français"
    },

    // Achat rapide
    quickBuy: {
        p1: "⛽️ Paramètres d'achat rapide.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "🦊 Configurez vos boutons d’achat rapide en personnalisant le montant de chaque bouton.",
        p5: "⚙️ Montant d'achat : (Sol)",
        p6: "💡 Choisissez un bouton d’achat rapide et indiquez le montant à lui attribuer.",
        p7: "🔃 Achat rapide",
        p8: "Transaction",
        p9: "Slippage",
        p10: "🟡 Achat en attente",
        p11: "Capitalisation :",
        p12: "🟢 Achat réussi",
        p13: "Voir sur Solscan",
        p14: "Wallet",
        p15: "Token",
        p16: "Voir sur Etherscan",
        viewToken: "🔄 Voir le Token",
        positions: "📊 Positions",
        sell: "🎒 Vendre",
        enterBuyAmountEth: "Entrez le montant d'achat en ETH pour le bouton {index} :",
        invalidAmountEth: "Montant invalide. Veuillez entrer un nombre valide."
    },

    // Vente rapide
    quickSell: {
        p1: "⛽️ Paramètres de vente rapide.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "🦊 Configurez vos boutons de vente rapide en personnalisant le pourcentage de chaque bouton.",
        p5: "⚙️ Pourcentages de ventes : (%)",
        p6: "💡 Choisissez un bouton de vente rapide et indiquez le pourcentage à lui attribuer.",
        p7: "🔃 Vente rapide",
        p8: "Transaction",
        p9: "Montant :",
        p10: "Montant de vente :",
        p11: "Slippage",
        p12: "🟡 Vente en attente",
        p13: "Solde en Tokens :",
        p14: "Montant de vente :",
        p15: "Capitalisation :",
        p16: "🟢 Vente réussie",
        p17: "Voir sur Solscan",
        p18: "Wallet",
        p19: "Voir sur Etherscan",
        viewToken: "🔄 Voir le Token",
        positions: "📊 Positions",
        buy: "💰 Acheter",
        tokenBalance: "Solde en Tokens :",
        selling: "Vente :"
    },

    // Vente automatique
    autoSell: {
        p1: "⛽️ Paramètres de vente automatique.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "🦊 Lorsque la vente automatique est activée, FoxyBoTracker exécutera automatiquement la vente de l’ensemble des Tokens concernés, conformément aux règles que vous avez définies.",
        p5: "Par défaut",
        p6: "📈 Niveau de Take Profit :",
        p7: "📉 Niveau de Stop loss :",
        p8: "💡 Configurez vos paramètres de vente automatique ci-dessous :",
        status1: "Activé",
        status2: "Désactivé",
        wallet: "💳 Wallet :",
    },

    // Tp & Sl
    TpSl: {
        p1: "💸 Réglages de Take profit & Stop loss automatiques.",
        p2: "❓ Si vous avez besoin d'aide",
        p3: "Cliquez ici !",
        p4: "🦊 Une fois un ordre d’achat exécuté avec succès, FoxyBoTracker créera automatiquement un ordre de vente basé sur vos paramètres de Take Profit ou de Stop Loss.",
        p5: "📈 Niveau de Take profit : ",
        p6: "📉 Niveau de Stop loss : ",
        p7: "💡 Ajoutez un nouveau Stop loss ou un nouveau Take profit ci-dessous :",
        tp: "📈 Take profit : ",
        sl: "📉 Stop loss : "
    },

    // Retrait
    withdrawal: {
        p1: "💳 Retrait",
        p2: "Transaction",
        p3: "Retrait en attente",
        p4: "Voir sur Solscan",
        p5: "Échec du retrait",
        p6: "Retrait réussi",
        p7: "💸 Confirmer le retrait",
        p8: "De",
        p9: "À",
        p10: "Montant :",
        p11: "💡 Souhaitez-vous confirmer ce retrait ?",
        confirm: "✅ Confirmer",
        view: "Voir la Transaction"
    },

    image: {
        buy: "Achat de Tokens",
        sell: "Vente de Tokens",
        gain: "Gain/Perte",
        date: "Date de vente",
    },

    trending: {
        p1: "🚀 Token(s) Tendance",
        p2: "🔥 Top 10 des Tokens du moment :",
        p3: "Rang",
        p4: "💠 Nom du Token",
        p5: "🆔 Adresse du Token",
        p6: "🪙 Liquidité",
        p7: "💲 Volume sur 24h",
        p8: "💹 Variation de volume",
        p9: "💰 Prix",
        next: "⏭️ Suivant",
        previous: "⏮️ Précédent"
    },

    // Subscribe
    subscribe: {
        title: "Options d'Abonnement",
        options: "Options d'Abonnement",
        unlockFeatures: "Débloquez des fonctionnalités premium :",
        sniping: "Sniping",
        choosePlan: "Choisissez le plan qui vous convient le mieux :",
        alreadySubscribed: "Vous êtes déjà abonné !",
        plan: "Plan",
        started: "Commencé",
        expiresIn: "Expire dans",
        subscriptionRequired: "Activation du système d'abonnement utilisateurs",
        pressSubscribe: "Appuyez sur le bouton *S'abonner* dans le menu principal pour activer votre abonnement.",
        walletNotConfigured: "Le Wallet d'abonnement n'est pas configuré. Veuillez contacter le support.",
        userNotFound: "Impossible de trouver votre enregistrement utilisateur. Veuillez réessayer /start.",
        addWalletFirst: "Veuillez ajouter et activer un Wallet avant de vous abonner.",
        insufficientSol: "SOL insuffisant.",
        insufficientEth: "ETH insuffisant.",
        needed: "Nécessaire",
        available: "Disponible",
        subscriptionSuccessful: "Abonnement réussi !",
        txid: "TXID",
        activeUntil: "Actif jusqu'à",
        subscriptionFailed: "Échec de l'abonnement. Veuillez réessayer plus tard.",
        subscribeButton: "💳 S'abonner",
        backToMenu: "⬅️ Retour Menu",
        week: "📅 1 Semaine",
        month: "⏱️ 1 Mois",
        year: "📅 1 An",
    },

    // Sniper
    sniper: {
        active: "🚀 SNIPER ACTIF — Prêt à sniper les nouveaux listings. Restez vigilant !",
        stopped: "🛑 Sniper arrêté — Surveillance en pause.",
        detectedActiveTokens: "🔥 Tokens actifs détectés :",
        noDetectedTokens: "Aucun Token actif détecté.",
        panelDescription: "Ce panneau correspond au module de Snipping. Il permet de configurer tous les paramètres liés au Snipping sur FoxyBoTracker.",
        panelDescription2: "Pour toute question, n’hésitez pas à nous contacter via notre site officiel ou la section d’aide.",
        exampleLink: "Cliquez ici",
        important: "Important :",
        importantNote: "Aucune garantie de profit n’est associée à FoxyBoTracker. Son utilisation relève de votre entière responsabilité.",
        tokenDetection: "🌍 Détect. Token",
        startSnipping: "Démarrer Snipping",
        stopSnipping: "Arrêter le Snipping",
        slippage: "Slippage",
        buy: "Acheter",
        buyLimit: "Limite d'Achat",
        takeProfit: "Take Profit",
        stopLoss: "Stop Loss",
        timeLimit: "Limite de temps",
        allowAutoBuy: "Achat Auto",
        allowAutoSell: "Vente Auto",
        advance: "⬆️ Réglages Avancés",
        advanceDown: "⬇️ Réglages Avancés",
        enableTwitterChannel: "Activer le Canal Twitter",
        disableTwitterChannel: "Désactiver le Canal Twitter",
        bondingCurveMin: "BC Min",
        bondingCurveMax: "BC Max",
        minMC: "MC Min",
        maxMC: "MC Max",
        minTokenAge: "Âge Min Token",
        maxTokenAge: "Âge Max Token",
        minHolders: "Dét. Min",
        maxHolders: "Dét. Max",
        minVolume: "Vol. Min",
        maxVolume: "Vol. Max",
        minLiquidity: "Liq. Min",
        maxLiquidity: "Liq. Max",
        minTXNS: "TXNS Min",
        maxTXNS: "TXNS Max",
        sniperButton: "🔫 Sniper 🔫",
        sniperButtonLocked: "🔒 Module Sniper Verrouillé 🔒",
        tokenDetectionList: "C'est la liste des Tokens détectés par la détection de FoxyBoTracker selon vos paramètres.",
        tokenInfoInstruction: "Vous pouvez voir les informations du Token en cliquant sur le lien du Token ci-dessous.",
        unknownToken: "Token inconnu",
        detailsUnavailable: "détails indisponibles",
        buyToken1: "Acheter - 1",
        buyToken2: "Acheter - 2",
        buyToken3: "Acheter - 3",
        buyToken4: "Acheter - 4",
        buyToken5: "Acheter - 5",
        lastRefreshed: "🕐 Dernière actualisation :",
        tokenStatus: "Statut du Token",
        tokenStatusMigrated: "🔄 Migré (Pump Swap)",
        tokenStatusOnBonding: "🆕 Sur Bonding Curve",
        tokenStatusBoth: "🌐 Les Deux",
        view: "Voir",
        price: "Prix",
        marketCap: "MCap",
        minutes: "min",
        enterBuyLimit: "Entrez le nombre d'achats. Si vous entrez 1, FoxyBoTracker échangera le Token une seule fois.",
        enterTakeProfit: "Entrez le montant du Take profit.",
        enterStopLoss: "Entrez le montant du Stop loss.",
        enterTimeLimit: "Entrez une limite de temps. Si vous entrez 10, FoxyBoTracker vendra vos Tokens après 10 minutes.",
        enterBondingCurveMin: "Entrez le pourcentage minimum de Bonding Curve.",
        enterBondingCurveMax: "Entrez le pourcentage maximum de Bonding Curve.",
        enterMinMarketCap: "Entrez la capitalisation boursière minimum",
        enterMaxMarketCap: "Entrez la capitalisation boursière maximum",
        enterMinTokenAge: "Entrez l'âge minimum du Token en minutes.",
        enterMaxTokenAge: "Entrez l'âge maximum du Token en minutes.",
        enterMinHolders: "Entrez le nombre minimum de détenteurs.",
        enterMaxHolders: "Entrez le nombre maximum de détenteurs.",
        enterMinVolume: "Entrez le volume minimum.",
        enterMaxVolume: "Entrez le volume maximum.",
        enterMinLiquidity: "Entrez la liquidité minimum.",
        enterMaxLiquidity: "Entrez la liquidité maximum.",
        enterMinTransactions: "Entrez le nombre minimum de Transactions.",
        enterMaxTransactions: "Entrez le nombre maximum de Transactions.",
        stopLossLabel: "💸 Stop Loss :",
    },

    // Snipping Settings (Admin)
    snippingSettings: {
        title: "Paramètres de Snipping",
        subscriptionRequired: "Requis",
        subscriptionNotRequired: "Non Requis",
        week: "Semaine",
        month: "Mois",
        year: "An",
        subscriptionRequirement: "Exigence de l'Abonnement",
        manageDescription: "Gérer les paramètres d'abonnement au module de Snipping et des utilisateurs de la Whitelist.",
    },

    // Messages
    messages: {
        accessDenied: "Accès refusé. Vous n'êtes pas dans la Whitelist.",
        addRemoveUser: "Veuillez saisir l'ID Telegram de l'utilisateur.",
        removed1: "✅ Utilisateur avec l'ID Telegram",
        removed2: "a été supprimé.",
        useradd: "✅ Utilisateur ajouté avec succès",
        addRemoveSniperUser: "Veuillez saisir l'ID Telegram (Numéro) ou le nom d'utilisateur (Avec ou sans @) de l'utilisateur.",
        removedSniperUser1: "✅ Utilisateur Sniper avec l'ID",
        removedSniperUser2: "a été supprimé de la Whitelist du module Sniper.",
        sniperUseradd: "✅ Utilisateur ajouté à la Whitelist du module Sniper avec succès",
        successLog: "✅ Vous vous êtes connecté avec succès. Bienvenue sur",
        buy: "Répondez avec une adresse de Token à acheter.",
        sell: "Répondez avec une adresse de Token à vendre.",
        buy_x: "Répondez avec le montant de SOL que vous souhaitez Trader.",
        buy_x_ethereum: "Répondez avec le montant d'ETH que vous souhaitez Trader.",
        sell_x: "Répondez avec le pourcentage de Tokens que vous souhaitez Trader. 10 -> 10%, 20 -> 20%",
        withdraw1: "Veuillez entrer le montant que vous souhaitez retirer. (En SOL) - Exemple : 5",
        withdraw1_ethereum: "Veuillez entrer le montant que vous souhaitez retirer. (En ETH) - Exemple : 5",
        withdraw2: "Veuillez entrer l'adresse du Wallet vers laquelle vous souhaitez retirer.",
        createName: "Veuillez entrer le nom de votre nouveau Wallet.",
        createSuccess1: "✅ Wallet",
        createSuccess2: "créé avec succès !",
        renameWallet1: "Veuillez entrer le nom du Wallet.",
        renameWallet2: "✅ Nom du Wallet mis à jour avec succès en",
        deleteWallet1: "✅ Wallet",
        deleteWallet2: "a été supprimé avec succès.",
        deleteWallet3: "🔄 Actualisation de la liste des Wallets...",
        positionImport1: "Entrez l'adresse du Token de la position que vous souhaitez importer.",
        positionImport2: "Ce Token n'existe pas",
        feeinput: "Veuillez saisir la valeur des frais (0-1).",
        slippageInput: "Veuillez entrer le pourcentage de Slippage compris entre (0-100).",
        youngInput: "Veuillez définir un seuil d’ancienneté du Token compris entre 1 et 24 heures. Une alerte de prudence s’affichera lors de l’achat si le Token détecté est plus récent que la limite définie.",
        quickBuy: "Veuillez entrer la nouvelle valeur de montant d'achat. (En SOL) - Exemple : 0.2",
        quickSell: "Veuillez entrer la nouvelle valeur de pourcentage de vente. (En %) - Exemple : 100",
        tp: "Veuillez entrer le pourcentage de niveau de Take profit : 10 -> 10%, 20 -> 20%",
        sl: 'Veuillez entrer le pourcentage de niveau de Stop loss : -10 -> -10%, -20 -> -20%',
        pnl: "✅ Génération de l'image PNL en cours...",
        importwallet1: "Le nom du Wallet ne peut pas contenir de symboles ou de caractères spéciaux.",
        importwallet2: "Un Wallet avec ce nom existe déjà. Veuillez réessayer.",
        importwallet3: "Veuillez entrer la clé privée du Wallet.",
        importwallet4: "Un Wallet avec cette clé privée existe déjà. Veuillez réessayer.",
        importwallet5: "Comment aimeriez-vous nommer votre nouveau Wallet ?",
        autoSell1: "🚀 Votre position a été clôturée automatiquement.",
        walletLimits: "Veuillez saisir la limite du Wallet !",
        autoSell2: "Token :",
        autoSell3: "💸 Take Profit atteint :",
        autoSell4: "🔁 Vente automatique à :",
        autoSell5: "🔁 Montant de la vente automatique à :",
        autoSell6: "Le marché a progressé et votre Take profit a été atteint, sécurisant vos gains.",
        autoSell7: "🛡️ Votre position a été clôturée automatiquement.",
        autoSell8: "🚫 Le marché a chuté et votre Stop loss a été déclenché, limitant vos pertes et protégeant votre capital restant.",
        entertip: "Veuillez saisir le pourcentage de pourboire compris entre (0-100).",
        referral1: "🎉 Votre ami",
        referral2: "a rejoint FoxyBoTracker via votre lien de parrainage !",
        referral3: "Bienvenue ! Vous avez rejoint FoxyBoTracker avec le lien de parrainage de l'utilisateur",
        enterreferral: "Veuillez entrer la récompense par parrainage en SOL !",
        enterreferral_ethereum: "Veuillez entrer la récompense par parrainage en ETH !",
        enterreferralSettings: "Veuillez entrer la valeur des paramètres de parrainage ! (Supérieure à 0)",
        refreshLimit: "⚠️ Trop de rafraîchissements. Veuillez ralentir.",
        refreshwarning: "⚠️ Attention ⚠️",
        fee: "Les frais de réseau sont automatiquement déduit"
    },

    // Erreurs
    errors: {
        invalidId: "❌ ID Telegram invalide. Veuillez entrer un ID utilisateur Telegram ou un nom d'utilisateur.",
        targetUser: "❌ Cet utilisateur Telegram n'existe pas dans la Whitelist.",
        invalidAddress: "❌ Erreur de validation : L'adresse du Token Solana que vous avez saisie est invalide. Veuillez vérifier et réessayer.",
        removederror: "⚠️ Une erreur est survenue lors de la tentative de suppression de l'utilisateur.",
        logError: "❌ Vous n'êtes pas autorisé à utiliser FoxyBoTracker. Veuillez contacter l'administrateur.",
        invalidAmount: "❌ Erreur de validation : Montant invalide. Réessayez !",
        invalidSellAmount: "❌ Erreur de validation : Montant du Trade invalide. Veuillez entrer une valeur entre 1 et 100.",
        invalidPrivateKey: "❌ Clé privée invalide. Veuillez fournir une clé privée valide.",
        errorOccurred: "❌ Une erreur s'est produite. Veuillez réessayer.",
        walletNotFound: "❌Il doit y avoir au moins un Wallet créé.",
        insufficientBalance: "❌ Solde insuffisant.",
        invalidWithdrawal: "Montant de retrait invalide. Veuillez réessayer.",
        invalidwallet: "Adresse de Wallet invalide. Veuillez réessayer.",
        invalidselection: "❌ Sélection de Wallet invalide.",
        invalidsecretkey: "❌ Le Wallet n'a pas de clé privée ou clé publique valide.",
        invalidwWalletName1: "❌ Le Nom du Wallet invalide. Veuillez réessayer.",
        invalidwWalletName2: "❌ Un Wallet avec ce nom existe déjà. Veuillez choisir un nom différent.",
        invalidUser: "❌ Utilisateur non trouvé. Veuillez réessayer plus tard.",
        invalidCopy1: "❌ Impossible de trouver le Wallet à copier.",
        invalidCopy2: "❌ Aucune clé privée disponible.",
        invalidFee: "❌ Erreur de validation : Frais non valides. Réessayez !",
        invalidSlippage: "❌ Erreur de validation : Pourcentage de Slippage invalide. Réessayez !",
        invalidyoung: "❌ Erreur de validation : Date invalide. Vous devez entrer un nombre entre 1 et 24. Réessayez !",
        invalidBuy: "Montant d'achat invalide.",
        invalidSell: "Pourcentage de vente invalide.",
        invalidAutoWallet: "❌ Aucun Wallet disponible à définir par défaut.",
        invalidTp: "❌ Erreur de validation : Valeur non valide. Veuillez saisir une valeur supérieure à 0. Réessayez !",
        invalidSl: "❌ Erreur de validation : Valeur non valide. Veuillez saisir une valeur inférieure à 0. Réessayez !",
        alreadyWhitelist: "⚠️ L'utilisateur est déjà dans la Whitelist !",
        alreadySniperWhitelist: "⚠️ L'utilisateur est déjà dans la Whitelist du module de Snipping !",
        targetSniperUser: "❌ Cet utilisateur Telegram n'existe pas dans la Whitelist du module de Snipping.",
        userNotFound: "❌ Utilisateur introuvable. Veuillez vérifier le nom d'utilisateur ou l'ID utilisateur et réessayer.",
        notToken: "Token introuvable",
        transactionFailed: "❌ Transaction échouée : Solde du Wallet faible ou transaction non confirmée en 60 secondes",
        transactionError: "❌ Erreur : Solde de Token faible ou Token non acheté.",
        insufficientFundsForGas: "Fonds insuffisants pour le gaz. Requis : {required} ETH pour les frais de gaz. Disponible : {available} ETH. Manque : {shortfall} ETH",
        insufficientFundsForSwap: "Fonds insuffisants. Requis : {required} ETH ({swapAmount} ETH pour l'échange + {gasAmount} ETH pour le gaz). Disponible : {available} ETH. Manque : {shortfall} ETH",
        insufficientFundsSimple: "❌ Fonds insuffisants !\nRequis : {required} ETH\nDisponible : {available} ETH",
        invalidtip: "❌ Erreur de validation : Pourcentage de pourboire invalide. Veuillez saisir une valeur comprise entre 0 et 100.",
        walletLimit: "❌ Limite de Wallets atteinte. Vous ne pouvez pas créer plus de",
        invalidwallets: "❌ Erreur de validation : Limites de Wallet non valides. Veuillez saisir une valeur comprise entre 1 et 100.",
        invalidsettings: "❌ Erreur de validation : Paramètres de parrainage non valides. Veuillez saisir une valeur supérieure à 0.",
    },

    // Bundle Wallets
    bundleWallets: {
        // Menu
        menuTitle: "Gestion des Wallets Groupés",
        menuDescription: "Choisissez une option de Wallet :",
        safeBundler: "Regroupement Sécurisé",
        maxWallets: "Maximum 20 Wallets",
        fasterExecution: "Exécution plus rapide",
        bestForOperations: "Idéal pour les opérations groupées",
        currentWallets: "Wallets groupés actuels",
        chooseOption: "Choisissez une option de Wallet :",
        viewWallets: "👀 Voir les Wallets",
        createWallets: "🆕 Créer des Wallets",
        fundWallets: "💰 Financer les Wallets",
        cleanFundBundles: "🧼 Nettoyer les Fonds Groupés",
        withdrawFromBundles: "⬆️ Retirer des Groupes",
        resetBundledWallets: "♻️ Réinitialiser les Wallets Groupés",
        backToBundleWallets: "⬅️ Retour Wallets Groupés",
        
        // View
        bundleWalletsTitle: "Wallets Groupés",
        noBundleWallets: "Aucun Wallet Groupé",
        noBundleWalletsDesc: "Vous n'avez pas encore de Wallets groupés.\n\nCliquez sur \"Créer des Wallets\" pour commencer.",
        totalWallets: "Total",
        walletNumber: "Wallet #",
        address: "Adresse",
        sol: "SOL",
        eth: "ETH",
        tokens: "Tokens",
        noTokens: "Aucun",
        errorLoading: "Erreur de chargement",
        
        // Create
        createTitle: "Créer des Wallets Groupés",
        howManyWallets: "Combien de Wallets groupés souhaitez-vous créer ?",
        maxWalletsNote: "(Max : 20 Wallets)",
        invalidCount: "Nombre Invalide",
        invalidCountDesc: "Le regroupement sécurisé prend en charge un maximum de",
        selectedWallets: "Wallets",
        all: "Tous",
        youSelectedCount: "Vous avez sélectionné",
        pleaseSelectMaxOrFewer: "Veuillez sélectionner {max} Wallets ou moins.",
        youSelectedForBundler: "Vous avez sélectionné {count} Wallets pour {bundler}",
        clickToProceed: "Cliquez sur \"{button}\" pour continuer :",
        creatingWallets: "Création de",
        congratulations: "Félicitations !",
        walletsCreated: "Wallets ont été créés avec succès pour",
        savePrivateKeys: "Veuillez sauvegarder vos clés privées en toute sécurité. Elles ne seront plus affichées !",
        invalidWalletCount: "Nombre de Wallets invalide. Veuillez sélectionner entre 1 et 20 Wallets.",
        pleaseEnterValidNumber: "Veuillez entrer un nombre valide.",
        walletKeysTitle: "Clés Privées des Wallets Bundle",
        storeSecurely: "Stockez ce fichier dans un endroit sûr!",
        neverShare: "Ne partagez jamais vos clés privées avec qui que ce soit !",
        downloadAndSave: "Téléchargez et sauvegardez ce fichier immédiatement.",
        keysFileSent: "Le fichier contenant les clés privées de vos Wallets a été envoyé. Merci de le télécharger et de le conserver soigneusement, à l’abri des regards.",
        
        // Bundle Wallet Keys File
        bundleWalletKeysHeader: "🔑 CLÉS PRIVÉES DES WALLETS BUNDLE",
        dateLabel: "Date :",
        operationBundleCreation: "Opération : Création de Wallets Bundle",
        bundleTypeLabel: "Type de Bundle :",
        totalWalletsLabel: "Total de Wallets :",
        bundleWalletNumber: "WALLET BUNDLE #",
        publicKeyAddress: "Clé Publique (Adresse) :",
        privateKeyLabel: "Clé Privée :",
        solscanLabel: "Solscan :",
        importantKeepKeysSafe: "ALERTE SÉCURITÉ CRITIQUE",
        bundleWalletKeysDescription: "Ce fichier contient les CLÉS PRIVÉES complètes de vos Wallets Bundle.",
        loseKeysWarning: "PERTE = PERTE DÉFINITIVE - En cas de perte ou de vol, l’accès aux fonds sera IRRÉVERSIBLEMENT perdu.",
        storeFileSecure: "Conservez ce fichier hors ligne, dans un emplacement ultra-sécurisé (Clé USB chiffrée, coffre-fort, support physique).",
        neverShareKeys: "NE PARTAGEZ JAMAIS CE FICHIER - Toute personne y ayant accès peut voler 100 % de vos fonds, sans aucun recours possible.",

        
        // Recovery Keys File
        recoveryKeysHeader: "🔑 CLÉS DE RÉCUPÉRATION DES WALLETS TEMPORAIRES",
        operationCleanFunding: "Opération : Financement Propre des Bundles",
        totalAmountLabel: "Montant Total :",
        bundleWalletsLabel: "Wallets Bundle :",
        tempWalletsLabel: "Wallets Temporaires :",
        devWalletLabel: "Wallet Dev :",
        tempWalletNumber: "WALLET TEMP #",
        publicKeyLabel: "Clé Publique :",
        recoveryKeysDescription: "⚠️ IMPORTANT : Gardez ces clés en sécurité !",
        tempWalletsClosed: "Ces Wallets temporaires seront FERMÉS après la distribution.",
        recoveryInstructions: "Si la distribution échoue, vous pouvez récupérer les SOL en utilisant ces clés.",
        
        // Fund
        fundTitle: "Financer les Wallets Groupés",
        activeWallet: "Wallet Actif",
        balance: "Solde",
        bundles: "Groupes",
        enterAmount: "Entrez le montant à distribuer (En SOL) :",
        enterAmount_ethereum: "Entrez le montant à distribuer (En ETH) :",
        fundingInProgress: "Financement en cours\n\nVeuillez attendre que l'opération en cours se termine.",
        userNotFound: "Utilisateur introuvable. Veuillez d'abord utiliser la commande /start.",
        activeWalletNotConfigured: "Wallet actif non configuré. Veuillez d'abord définir un Wallet actif.",
        noBundleWalletsFound: "Aucun Wallet groupé trouvé. Créez d'abord des Wallets groupés.",
        invalidAmount: "Montant invalide. Veuillez entrer un nombre positif.",
        fundingAlreadyInProgress: "Financement déjà en cours.",
        startingDistribution: "Démarrage de la Distribution Propre",
        amount: "Montant",
        wallets: "Wallets",
        status: "Statut",
        insufficientAmount: "Montant Insuffisant",
        provided: "Fourni",
        required: "Requis",
        breakdown: "Détails",
        distribution: "Distribution",
        feesReserves: "Frais et réserves",
        addMore: "de plus",
        insufficientBalance: "Solde Insuffisant",
        available: "Disponible",
        pleaseAdd: "Veuillez ajouter",
        toActiveWallet: "à votre Wallet actif.",
        
        // Clean Fund
        cleanFundTitle: "Nettoyer les Fonds Groupés",
        cleanFundDesc: "Cela récupérera tout SOL restant des Wallets temporaires utilisés pendant le financement.",
        cleanFundDesc_ethereum: "Cela récupérera tout ETH restant des Wallets temporaires utilisés pendant le financement.",
        mayTakeMoment: "Cette opération peut prendre quelques instants...",
        cleanFundComplete: "Opération de nettoyage des fonds groupés terminée.",
        tempWalletsCleaned: "Tous les Wallets temporaires ont été nettoyés pendant le processus de financement.",
        
        // Withdraw
        withdrawTitle: "Retirer des Groupes",
        activeBalance: "Solde Actif",
        totalWithdrawable: "Total Retirable",
        fromWallets: "De",
        willWithdrawAll: "Cela retirera TOUS les fonds retirables de tous les Wallets groupés.",
        typeConfirm: "Tapez le mot \"CONFIRM\" pour continuer :",
        withdrawalCancelled: "Retrait annulé. Tapez la commande CONFIRM pour continuer.",
        withdrawingFunds: "Retrait des fonds des Wallets groupés...",
        processing: "Traitement",
        processed: "Traité",
        totalWithdrawn: "Total Retiré",
        withdrawalComplete: "Retrait Terminé",
        successfullyWithdrew: "Retrait réussi de",
        fundsInActiveWallet: "Les fonds sont maintenant dans votre Wallet actif.",
        noWithdrawableFunds: "Aucun Fonds Retirable",
        allWalletsInsufficient: "Tous les Wallets groupés ont un solde insuffisant pour retirer.",
        needRentExempt: "(Besoin de conserver le minimum exonéré de loyer + Frais de Transaction)",
        
        // Reset
        resetTitle: "Réinitialiser les Wallets Groupés",
        resetWarning: "ATTENTION : Cela supprimera TOUS les",
        willDeleteAll: "Wallets groupés !",
        cannotBeUndone: "Cette action ne peut pas être annulée.",
        savePrivateKeysIfNeeded: "Assurez-vous d'avoir sauvegardé toutes les clés privées si nécessaire.",
        typeReset: "Tapez le mot \"RESET\" pour confirmer :",
        resetCancelled: "Réinitialisation annulée. Tapez la commande RESET pour confirmer.",
        resetComplete: "Wallets Groupés Réinitialisés",
        allWalletsDeleted: "Wallets groupés ont été supprimés.",
        noBundleWalletsToReset: "Aucun Wallet groupé à réinitialiser.",
        
        // Buy/Sell
        noBundleWalletsForBuy: "Aucun Wallet Groupé",
        needCreateFirst: "Vous devez d'abord créer des Wallets groupés.",
        goToCreate: "Allez dans Wallets → Wallets Groupés → Créer des Wallets",
        bundleBuyStarted: "Achat Groupé Démarré",
        token: "Token",
        usingAllBalance: "Utilisation de TOUT le solde disponible de chaque Wallet",
        walletsWithBalance: "Wallets avec solde",
        bundleBuy: "Achat Groupé",
        success: "Succès",
        failed: "Échoué",
        bundleBuyComplete: "Achat Groupé Terminé",
        successful: "Réussi",
        totalBought: "Total acheté",
        successfulTransactions: "Transactions Réussies",
        failedWallets: "Wallets Échoués",
        insufficientBalanceForBuy: "Solde Insuffisant",
        noneHaveEnoughSol: "Aucun de vos Wallets groupés n'a assez de SOL pour exécuter cet achat.",
        needAtLeast: "(Besoin d'au moins 0.001 SOL après le minimum exonéré de loyer)",
        needAtLeast_ethereum: "(Besoin d'au moins 0.0001 ETH après les frais de gaz)",
        bundleSellStarted: "Vente Groupée Démarrée",
        selling: "Vente de",
        percentOfBalance: "du solde de Token de chaque Wallet",
        checkingBalances: "Vérification des soldes...",
        noTokenBalance: "Aucun Solde de Token",
        noneHaveToken: "Aucun de vos Wallets groupés n'a ce Token.",
        foundTokensIn: "Tokens trouvés dans",
        bundleSell: "Vente Groupée",
        bundleSellComplete: "Vente Groupée Terminée",
        sold: "Vendu",
        activeWalletNotConfiguredBuy: "Wallet actif non configuré.",
        
        // Funding process messages
        recoveryKeysTitle: "CLÉS DE RÉCUPÉRATION - CONSERVEZ EN SÉCURITÉ !",
        recoveryKeysCaption: "Ce sont les clés de vos Wallets temporaires.",
        recoveryKeysWarning: "Téléchargez et sauvegardez ce fichier immédiatement !",
        recoveryKeysDownload: "Téléchargez et sauvegardez ce fichier immédiatement !",
        recoveryKeysRecover: "Vous pouvez récupérer les fonds si quelque chose échoue.",
        recoveryKeysStart: "Le financement commencera dans 5 secondes...",
        criticalError: "ERREUR CRITIQUE",
        failedToSendRecovery: "Échec de l'envoi des clés de récupération à Telegram.",
        operationAborted: "Opération annulée pour des raisons de sécurité.",
        checkInternetConnection: "Veuillez vérifier votre connexion Internet et réessayer.",
        cleanDistribution: "Distribution Propre",
        validated: "Validé",
        distributable: "SOL distribuable",
        distributable_ethereum: "ETH distribuable",
        creatingTempWallets: "Création de",
        phase: "Phase",
        fundingTemps: "Financement des temporaires",
        tempWallets: "Wallets temporaires",
        funded: "financé",
        fundingFailed: "Échoué",
        couldNotFundTempWallets: "Impossible de financer les Wallets temporaires.",
        phaseComplete: "terminé",
        tempsFunded: "temporaires financés",
        breakingHeuristics: "Rupture des heuristiques...",
        heuristics: "Heuristiques",
        fundingBundles: "Groupes",
        allTempWalletsExhausted: "Tous les Wallets temporaires épuisés au groupe",
        distributionIncomplete: "Distribution Incomplète",
        someBundlesNotFunded: "Certains groupes n'ont pas pu être financés en raison d'une distribution de solde insuffisante.",
        checkRecoveryKeys: "Vérifiez votre fichier de clés de récupération - Il contient l'accès à tous les fonds restants dans les Wallets temporaires.",
        bundleNumber: "Groupe #",
        fundingComplete: "Financement Terminé !",
        fundingSuccess: "Succès",
        perWallet: "Par Wallet",
        accountsClosed: "Comptes fermés",
        recovered: "Récupéré",
        transactionExplorer: "Explorateur de Transactions",
        tempFunding: "Financement Temporaire",
        wsolOperations: "Opérations WSOL",
        bundleDistribution: "Distribution des Groupes",
        accountClosure: "Fermeture de Compte",
        allTempAccountsClosed: "Tous les comptes temporaires fermés et supprimés de la Blockchain !",
        bundleWalletsReady: "Vos Wallets groupés sont financés et prêts !",
        viewOnSolscan: "Voir sur Solscan",
        distributingToBundles: "Distribution aux groupes",
        confirmingTransactions: "Confirmation des Transactions...",
        closingAccounts: "Fermeture des comptes...",
        bundleFunded: "financé",
        insufficient: "Insuffisant",
        
        // Button labels
        bundleBuyButton: "👜 Achat Groupé",
        bundleSellButton: "👜 Vente Groupée",
    },

    // Sélection de Chaîne
    chain: {
        selectBlockchain: "🔗 Sélectionner votre Blockchain",
        current: "Blockchain sélectionnée :",
        choosePreferred: "Sélectionnez la Blockchain sur laquelle vous souhaitez Trader avec FoxyBoTracker :",
        solana: "Solana",
        ethereum: "Ethereum",
        solanaSelected: "✅ Solana",
        ethereumSelected: "✅ Ethereum",
    },
};
